### ISSUE TITLE
teste issue 

### ISSUE THREAD

**Issue by pedroresendedev** [pedroresende15/RepoTeste#1]
testando issues aqui.

**Comment by pedroresende15** [comment]
Teste com sucesso!

**Comment by pedroresende15** [comment]
teste cpmentario apos fechamento

**Comment by pedroresendedev** [comment]
teste fechamento 2

**Comment by pedroresendedev** [comment]
Thank you for your collaboration! 

![img]()

More from me: 
- My personal [Instagram](https://www.instagram.com/pedregulho_resende/) account 
- My repository in [Github](https://github.com/pedroresendedev)
